# Generated by Django 5.2.12 on 2026-03-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('classification', models.CharField(choices=[('top_secret', '🔴 TOP SECRET'), ('classified', '🟠 CLASSIFIED'), ('confidential', '🟡 CONFIDENTIAL'), ('restricted', '🔵 RESTRICTED')], default='classified', max_length=20)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('leaked', 'LEAKED'), ('encrypted', 'ENCRYPTED'), ('deleted', 'DELETED - RECOVERED')], default='encrypted', max_length=20)),
                ('date_created', models.DateField()),
                ('agency', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_redacted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '🗂️ Classified File',
                'verbose_name_plural': '🗂️ Classified Files',
            },
        ),
    ]
